language: node_js
os:
  - linux
  - osx
node_js:
    - 8
    - 7
    - 6
    - 5
    - 4

cache:
  directories:
    - node_modules
    - ~/.npm
    - /usr/local/phantomjs
    - ~/.nvm

script:
  - npm run travis
  - npm prune

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

notifications:
  on_success: change
  on_failure: always

matrix:
  fast_finish: true
