language: node_js

sudo: false
dist: trusty

node_js:
  - "7"
  - "6"
  - "5"
  - "4"
  - "0.10"
  - "0.12"

cache:
  directories:
    - node_modules
    - ~/.npm
    - /usr/local/phantomjs

script:
  - npm test

after_success:
  - npm install coveralls@^2.11
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

notifications:
  on_success: change
  on_failure: always

branches:
  only:
    - master
    - develop