language: node_js
node_js:
    - "0.10"
    - "0.12"
    - "6"
    - "5"
    - "4"

cache:
  directories:
    - node_modules
    - ~/.npm
    - /usr/local/phantomjs

script: npm run travis

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

notifications:
  on_success: change
  on_failure: always

matrix:
  fast_finish: true

branches:
  only:
    - master
    - develop