language: node_js
sudo: false
node_js:
    - 8
    - 7
    - 6
    - 5
    - 4

cache:
  directories:
    - node_modules
    - /usr/local/phantomjs

script: npm run travis

before_install:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
